export const FETCH_PROJECTS_INIT = "FETCH_PROJECTS_INIT";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";
export const UPDATE_PROJECT = "UPDATE_PROJECT";

export const FETCH_USERS_INIT = "FETCH_USERS_INIT";
export const FETCH_PROJ_USERS_INIT = "FETCH_PROJ_USERS_INIT";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_PROJ_USERS_SUCCESS = "FETCH_PROJ_USERS_SUCCESS";
export const FETCH_PROJ_USERS_FAILURE = "FETCH_PROJ_USERS_FAILURE";
export const UPDATE_USERS = "UPDATE_USERS";
export const DELETE_PROJ_USERS = "DELETE_PROJ_USERS";
export const GET_PROJ_USERS = "GET_PROJ_USERS";
export const UPDATE_PROJ_USERS = "UPDATE_PROJ_USERS";
export const UPDATE_USER_ROLES = "UPDATE_USER_ROLES";

export const FETCH_PROJ_TICKETS_INIT = "FETCH_PROJ_TICKETS_INIT";
export const FETCH_PROJ_TICKETS_SUCCESS = "FETCH_PROJ_TICKETS_SUCCESS";
export const FETCH_PROJ_TICKETS_FAILURE = "FETCH_PROJ_TICKETS_FAILURE";
export const GET_TICKETS = "GET_TICKETS";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const ADD_TICKET = "ADD_TICKET";

export const FETCH_USER_TICKETS_INIT = "FETCH_USER_TICKETS_INIT";
export const FETCH_USER_TICKETS_SUCCESS = "FETCH_USER_TICKETS_SUCCESS";
export const FETCH_USER_TICKETS_FAILURE = "FETCH_USER_TICKETS_FAILURE";

export const DELETE_TICKET = "DELETE_TICKET";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
