export const FETCH_PROJECTS_INIT = "FETCH_PROJECTS_INIT";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";
export const FETCH_USERS_INIT = "FETCH_USERS_INIT";
export const FETCH_PROJ_USERS_INIT = "FETCH_PROJ_USERS_INIT";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_PROJ_USERS_SUCCESS = "FETCH_PROJ_USERS_SUCCESS";
export const FETCH_PROJ_USERS_FAILURE = "FETCH_PROJ_USERS_FAILURE";

export const FETCH_PROJ_TICKETS_INIT="FETCH_PROJ_TICKETS_INIT";
export const FETCH_PROJ_TICKETS_SUCCESS = "FETCH_PROJ_TICKETS_SUCCESS";
export const FETCH_PROJ_TICKETS_FAILURE = "FETCH_PROJ_TICKETS_FAILURE";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
